' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE which you
' should have received as part of this distribution.

class scalar_mod::scalar_type {
}

class scalar_real32_mod::scalar_real32_type {
  +value : real32

  <<create>>+scalar_constructor( <<in>>value:real32 ) : scalar_type

  +get_sum() : real32
  +get_min() : real32
  +get_max() : real32
  +reduction_finish()
}

class scalar_real64_mod::scalar_real64_type {
  +value : real64

  <<create>>+scalar_constructor( <<in>>value:real64 ) : scalar_type

  +get_sum() : real64
  +get_min() : real64
  +get_max() : real64
  +reduction_finish()
}

class scalar_int32_mod::scalar_int32_type {
  +value : int32

  <<create>>+scalar_constructor( <<in>>value:int32 ) : scalar_type

  +get_sum() : int32
  +get_min() : int32
  +get_max() : int32
  +reduction_finish()
}

scalar_mod::scalar_type -- scalar_real32_mod::scalar_real32_type
scalar_mod::scalar_type -- scalar_real64_mod::scalar_real64_type
scalar_mod::scalar_type -- scalar_int32_mod::scalar_int32_type
