export COUPLER=none
export DR_HOOK=false
export compile_atmos=preprocess-atmos
export config_revision=@vn10.7
export config_root_path=fcm:um.xm_tr
export config_type=atmos
export extract=extract
export fcflags_overrides=
export jules_rev=um10.7
export jules_sources=fcm:jules.xm_br/dev/richardgilham/vn4.8_qsat_refact\ fcm:jules.xm_br/dev/ianboutle/vn4.8_lfric_bug\ fcm:jules.xm_br/dev/ianboutle/vn4.8_lfric_bl_ifdef
export keys_atmos_extra=LFRIC=lfric
export land_surface_model=jules
export ldflags_overrides_prefix=
export ldflags_overrides_suffix=
export mpp_version=1C
export openmp=true
export optimisation_level=high
export platform_config_dir=meto-xc40-ifort
export portio_version=2A
export prebuild=
export socrates_rev=um10.7
export socrates_sources=
export solver_precision=double
export stash_version=1A
export steplist="extract preprocess-atmos"
export timer_version=3A
export um_rev=vn10.7
export um_sources=fcm:um.xm_br/dev/ianboutle/vn10.7_lfric_bl_ifdef\ fcm:um.xm_br/dev/richardgilham/vn10.7_qsat_refact\ fcm:um.xm_br/dev/ianboutle/vn10.7_lfric_exo_bugs
