' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.
@startuml

!include look.iuml
!include utilities/lfric_mpi_mod.iuml

lfric_mpi_mod::lfric_mpi_type *-- mpi_comm_type
lfric_mpi_mod::lfric_mpi_type .. lfric_mpi_mod::lfric_comm_type
lfric_mpi_mod::lfric_comm_type *-- mpi_comm_type
mpi_comm_type *-- mpi_val

@enduml
