' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class lfric_mpi_mod::lfric_mpi_type {
  -comm: mpi_comm_type
  -comm_size : integer
  -comm rank : integer
  -comm_set: logical

  +initialise(in_comm: lfric_comm_type)
  +finalise()
  +get_comm(): lfric_comm_type
  +is_comm_set(): Boolean
  +global_sum(l_sum: real64, g_sum: real64)
  +global_sum(l_sum: real32, g_sum: real32)
  +global_sum(l_sum: int32,  g_sum: int32)
  +global_min(l_min: real64, g_min: real64)
  +global_min(l_min: real32, g_min: real32)
  +global_min(l_min: int32,  g_min: int32)
  +global_max(l_max: real64, g_max: real64)
  +global_max(l_max: real32, g_max: real32)
  +global_max(l_max: int32,  g_max: int32)
  +all_gather(send_buffer: int32, recv_buffer: int32, count: int32)
  +broadcast(buffer(:): logical, count: integer, root: integer)
  +broadcast(buffer(:): int32, count: integer, root: integer)
  +broadcast(buffer(:): real64, count: integer, root: integer)
  +broadcast(buffer(:): real32, count: integer, root: integer)
  +broadcast(buffer(:,:): logical, count: integer, root: integer)
  +broadcast(buffer(:,:): int32, count: integer, root: integer)
  +broadcast(buffer(:,:): real64, count: integer, root: integer)
  +broadcast(buffer(:,:): real32, count: integer, root: integer)
  +broadcast(buffer(:,:,:): logical, count: integer, root: integer)
  +broadcast(buffer(:,:,:): int32, count: integer, root: integer)
  +broadcast(buffer(:,:,:): real64, count: integer, root: integer)
  +broadcast(buffer(:,:,:): real32, count: integer, root: integer)
  +broadcast(buffer: string, count: integer, root: integer)
  +get_comm_size(): integer
  +get_comm_rank(): integer
}
note right
This object encapsulates
all LFRic use of mpi
end note

class lfric_mpi_mod::lfric_comm_type {
  -comm: mpi_comm_type

  +get_comm_mpi_val(): integer
  +set_comm_mpi_val(comm: integer)
}
note right
This is defined in LFRic and
passed around the LFRic code
(including to the lfric_mpi_type initialiser)
end note

class mpi_comm_type {
  +mpi_val: integer
}
note left
This is defined in mpi_f08 and
given to any mpi_f08 code that
needs a communicator
end note

class mpi_val{
}
note left
This is a simple integer and is
given to any legacy mpi code
that needs a communicator
end note
