#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
# For further details please refer to the file LICENCE.original which you
# should have received as part of this distribution.
##############################################################################
'''
Wraps the biperiodic mesh generator so it may be controlled using command line
arguments.
'''

from __future__ import print_function;

import argparse
import os
import os.path
import subprocess
import sys
import tempfile

if __name__ == '__main__':
  parser = argparse.ArgumentParser( add_help=False, description='''
Generate a biperiodic mesh in UGRID format.

This commandline interface should be considered DEPRECATED. It will be replaced
in the future by a new, cleaner, one. It should certainly not be used within
scripts. Instead call the biperiodic_mesh_generator binary directly with a
suitible namelist.
'''.strip() )
  parser.add_argument( '-help', '-h', '--help', action='help', \
                       help='Display this message' )
  parser.add_argument( '-nx', metavar='INTEGER', \
                       default=5, help='Elements in X' )
  parser.add_argument( '-ny', metavar='INTEGER', \
                       default=4, help='Elements in Y' )
  parser.add_argument( '-dx', metavar='REAL', \
                       default=6000.0, help='Coordinate increment in X' )
  parser.add_argument( '-dy', metavar='REAL', \
                       default=2000.0, help='Coordinate increment in Y' )
  parser.add_argument( '-o', metavar='FILENAME', \
                       default='ugrid_quads_2d.nc', \
                       help='Mesh file to create' )
  arguments = parser.parse_args()

  namelist = '''
&biperiodic_mesh_generator
  cells_in_x    = {nx}
  cells_in_y    = {ny}
  cell_width    = {dx}
  cell_height   = {dy}
  mesh_filename = '{filename}'
  mesh_name = 'dynamics'
/
             '''.strip()

  handle, tempname = tempfile.mkstemp( suffix='.nml', text=True )
  try:
    with os.fdopen( handle, 'w' ) as temporaryFile:
      # GFortran doesn't like namelist files which do not have a newline after
      # the last namelist. Hence we add one, just in case.
      print( namelist.format( nx=arguments.nx, \
                              ny=arguments.ny, \
                              dx=arguments.dx, \
                              dy=arguments.dy, \
                              filename=arguments.o ) + '\n', \
             file=temporaryFile )

    command = [os.path.join( os.path.dirname(sys.argv[0]), \
                             'biperiodic_mesh_generator' ), tempname]
    subprocess.check_call( command )
  except Exception:
    exception, value, traceback = sys.exc_info()
    os.remove( tempname )
    raise value, None, traceback
