' (c) The copyright relating to this work is owned jointly by the Crown,
' Met Office and NERC 2014. However, it has been created with the help of the
' GungHo Consortium, whose members are identified at
' https://puma.nerc.ac.uk/trac/GungHo/wiki

class genbiperiodic_mod::genbiperiodic_type {

  -mesh_name: string
  -mesh_class: string
  -constructor_inputs: string
  -coord_units_x: string
  -coord_units_y: string
  -dx: real
  -dy: real
  -edge_cells_x: integer
  -edge_cells_y: integer
  -npanels: integer
  -nmaps: integer

  -target_mesh_names: string[:] <<allocatable>>
  -target_edge_cells_x: integer[:] <<allocatable>>
  -target_edge_cells_y: integer[:] <<allocatable>>
  -global_mesh_maps: global_mesh_map_collection_type <<allocatable>>

  -cell_next: integer[::] <<allocatable>>
  -verts_on_cell: integer[::] <<allocatable>>
  -edges_on_cell: integer[::] <<allocatable>>
  -verts_on_edge: integer[::] <<allocatable>>
  -vert_coords: real[::] <<allocatable>>
  -cell_coords: real[::] <<allocatable>>

  +<<create>>genbiperiodic_constructor( <<in>> mesh_name: string, <<in>> edge_cells_x: integer, <<in>> edge_cells_y: integer, <<in>> domain_x: integer, <<in>> domain_y: integer, <<in>> target_mesh_names: string[:] <<optional>>, <<in>> target_edge_cells_x: integer[:] <<optional>>, <<in>> target_edge_cells_y: integer[:] <<optional>> ): genbiperiodic_type

  +calc_adjacency( <<out>> cell_next:integer[::] <<allocatable>> )
  +calc_face_to_vert( <<out>> verts_on_cell: integer[::] <<allocatable>> )
  +calc_edges( <<out>> edges_on_cell: integer[::] <<allocatable>>, <<out>> verts_on_edge: integer[::] <<allocatable>> )
  +calc_coords( <<out>> vert_coords: real[::] <<allocatable>>, <<out>> coord_units_x: string, <<out>> coord_units_y: string )
  +calc_cell_centres()

  +generate( ... )
  +get_metadata( ... )
  +get_dimensions( ... )
  +get_coordinates( ... )
  +get_connectivity( ... )
  +get_global_mesh_maps( ... )

  +write_mesh()

}

genbiperiodic_mod::genbiperiodic_type -|> ugrid_generator_mod::ugrid_generator_type
