' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class gencube_ps_mod::gencube_ps_type {
  -mesh_name: string
  -mesh_class: string
  -constructor_inputs: string
  -coord_units_x: string
  -coord_units_y: string
  -edge_cells: integer
  -nsmooth: integer
  -npanels: integer
  -nmaps: integer

  -target_mesh_names: string[:] <<allocatable>>
  -target_edge_cells: integer[:] <<allocatable>>
  -global_mesh_maps: global_mesh_map_collection_type <<allocatable>>

  -cell_next: integer[::] <<allocatable>>
  -verts_on_cell: integer[::] <<allocatable>>
  -edges_on_cell: integer[::] <<allocatable>>
  -verts_on_edge: integer[::] <<allocatable>>
  -vert_coords: real[::] <<allocatable>>
  -cell_coords: real[::] <<allocatable>>

  +<<create>>gencube_ps_constructor( <<in>> mesh_name: string, <<in>> edge_cells: integer, <<in>> nsmooth: integer, <<in>> target_mesh_names: string[:] <<optional>>, <<in>> target_edge_cells: integer[:] <<optional>> ): gencube_ps_type

  +calc_adjacency ( <<out>> cell_next:integer[::] <<allocatable>> )
  +calc_face_to_vert ( <<out>> verts_on_cell:integer[::] <<allocatable>> )
  +calc_edges( <<out>> edges_on_cell: integer[::] <<allocatable>>, <<out>> verts_on_edge: integer[::] <<allocatable>> )
  +calc_coords( <<out>> vert_coords: real[::] <<allocatable>>, <<out>> coord_units_x: string, <<out>> coord_units_y: strinig )
  +calc_cell_centres()

  +generate( ... )
  +get_metadata( ... )
  +get_dimensions( ... )
  +get_coordinates( ... )
  +get_connectivity( ... )
  +get_global_mesh_maps( ... )

  +write_mesh()
  +orient_lfric()
  +smooth()

}

gencube_ps_mod::gencube_ps_type -|> ugrid_generator_mod::ugrid_generator_type
