' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE which you
' should have received as part of this distribution.

class ncdf_quad_mod::ncdf_quad_type {

  -ncid: integer
  -file_name: string
  -model_extents: integer
  -mesh_extents:  integer

  -mesh_name:     string
  -geometry:      string
  -coord_sys:     string
  -coord_units_x: string
  -coord_units_y: string
  -npanels:       integer

  -constructor_inputs: string

  -north_pole:  real[2]
  -null_island: real[2]
  -equatorial_latitude: real

  -nmesh_nodes:   integer
  -nmesh_edges:   integer
  -nmesh_faces:   integer
  -nmesh_targets: integer

  -partition_of:       string
  -inner_depth:        integer
  -halo_depth:         integer
  -num_edge:           integer
  -num_ghost:          integer
  -max_stencil_depth:  integer
  -last_edge_cell:     integer
  -last_ghost_cell:    integer
  -nmesh_faces_global: integer

  -num_inner:       integer[:] <<allocatable>>
  -last_inner_cell: integer[:] <<allocatable>>
  -num_halo:        integer[:] <<allocatable>>
  -last_halo_cell:  integer[:] <<allocatable>>
  -node_cell_owner: integer[:] <<allocatable>>
  -edge_cell_owner: integer[:] <<allocatable>>

  -global_var:  string
  -rim_depth:   integer
  -domain_size: real[2]
  -periodic_xy: logical[2]
  -topology:    string

  -cell_gid:         integer[:]  <<allocatable>>
  -node_on_cell_gid: integer[::] <<allocatable>>
  -edge_on_cell_gid: integer[::] <<allocatable>>

  -target_mesh_names:       string[:] <<allocatable>>
  -target_global_mesh_maps: global_mesh_map_collection_type <<pointer>>
  -target_local_mesh_maps:  local_mesh_map_collection_type  <<pointer>>

  -one_dim_id:             integer
  -two_dim_id:             integer
  -four_dim_id:            integer
  -nmesh_nodes_dim_id:     integer
  -nmesh_edges_dim_id:     integer
  -nmesh_faces_dim_id:     integer
  -nmesh_map_faces_dim_id: integer

  -ntargets_per_source_dim_id:   integer[:] <<allocatable>>
  -ntargets_per_source_x_dim_id: integer[:] <<allocatable>>
  -ntargets_per_source_y_dim_id: integer[:] <<allocatable>>

  -mesh_id:             integer
  -mesh_edge_nodes_id:  integer
  -mesh_face_nodes_id:  integer
  -mesh_face_edges_id:  integer
  -mesh_node_x_id:      integer
  -mesh_node_y_id:      integer
  -mesh_face_x_id:      integer
  -mesh_face_y_id:      integer
  -mesh_mesh_links_id:  integer[:] <<allocatable>>

  -partition_id:        integer
  -node_cell_owner_id:  integer
  -edge_cell_owner_id:  integer
  -num_inner_id:        integer
  -num_halo_id:         integer
  -last_inner_cell_id:  integer
  -last_halo_cell_id:   integer
  -n_inner_dim_id:      integer
  -n_halos_dim_id:      integer
  -global_mesh_id:      integer
  -global_cells_id:     integer
  -global_face_node_id: integer
  -global_face_edge_id: integer
  -domain_size_id:      integer

  -void_cell: integer

  +read_mesh( ... )
  +read_map( ... )
  +write_mesh( ... )
  +append_mesh( ... )
  +get_dimensions( ... )
  +get_mesh_names( ... )
  +get_n_meshes( ... )
  +is_mesh_present( ... )
  +file_close( ... )
  +file_new( ... )
  +file_open( ... )

}

ugrid_file_mod::ugrid_file_type <|.left. ncdf_quad_mod::ncdf_quad_type
