@startuml

!include look.iuml
!include gungho/field_mod.iuml
!include gungho/function_space_mod.iuml
!include utils/linked_list_data_mod.iuml
!include gungho/function_space_collection_mod.iuml
!include gungho/quadrature_mod.iuml
!include gungho/operator_mod.iuml
!include gungho/scalar_mod.iuml

field_mod::field_type o---> function_space_mod::function_space_type

function_space_mod -[hidden]- quadrature_mod : layout
function_space_mod -[hidden]- operator_mod : layout

@enduml
