#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''!
Extract commit messages from Subversion as a Gource captions file.
'''

from __future__ import print_function

import argparse
import re
import doctools.subversive

def version():
    '''!
    This application's version number.

    @return (str) The version number.
    '''
    return '1.0.0'

def encaptor( target, outputName ):
    '''!
    Generates a Gource captions file from a Subversion repository.

    @param target (str) Either a repository URL or working copy path.
    @param outputName (str) Filename for the captions file.
    '''
    standardPattern = re.compile( r'#\d+ for [^:.-]+.\s*([^.?!\n]+)(.?).*$', \
                                  flags=re.MULTILINE|re.IGNORECASE )
    simplePattern   = re.compile( r'([^.?!]+)(.?).*$', flags=re.MULTILINE )

    with open(outputName, 'w') as output:
        events = doctools.subversive.subversionLog( target )
        for timestamp in sorted( events.keys() ):
            logText = events[ timestamp ]

            match = standardPattern.match( logText )
            if not match :
                match = simplePattern.match( logText )

            if not match :
                reason = 'Unable to extract a message from "{}"'
                raise UserException( reason.format( logText ) )

            message = match.group( 1 )
            if match.group( 2 ) :
                terminator = match.group( 2 )
            else :
                terminator = '.'
            message = message[ 0:1 ].upper() + message[ 1: ]
            print( '{}|{}{}'.format( str( timestamp ), message, terminator ), \
                    file=output)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help = False, \
             description='Extract Gource captions from Subversion working copy')
    parser.add_argument('-help', '-h', '--help', action='help', \
                        help='Display this help message.')
    parser.add_argument('-version', action='version', \
                        version='%(prog)s {}'.format(version()), \
                        help='Display version information.')
    parser.add_argument('target', \
                        help='Either a working copy of repository URL to log.')
    parser.add_argument('outputFilename', metavar='filename', \
                        help='The caption file to write.')
    args = parser.parse_args()

    encaptor(args.target, args.outputFilename)
