#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''
Generate a make file snippet holding build information about a source file.

This snippet consists of a dependency list built up from the modules a
file "use"s.

This snippet may then be "include"ed into other make files.
'''

from __future__ import print_function;

import argparse
import os
import sys

from dependerator import __version__
import dependerator.analyser as analyser
import dependerator.database as database
import utilities.logging  as logging

###############################################################################
# Entry point

if __name__ == '__main__':
    parser = argparse.ArgumentParser( add_help=False, \
                                      description=__doc__ )
    parser.add_argument( '-help', '-h', '--help', action='help', \
                         help='Show this help message and exit' )
    parser.add_argument( '-version', action='version', \
                         version='%(prog)s {}'.format( __version__ ) )
    parser.add_argument( '-verbose', action='store_true', \
                         help='Provide a running commentry' )
    parser.add_argument( '-ignore', metavar='MODULE', action='append', \
                         help='A 3rd party module name to be ignored. ' \
                              + 'This may appear multiple times.' )
    parser.add_argument( 'database', metavar='database-file', \
                         help='Database file to use' )
    parser.add_argument( 'source', metavar='source-file', \
                         help='The source file.' )
    args = parser.parse_args()

    if args.verbose:
        logger = logging.PrintLogger( sys.stdout )
    else:
        logger = logging.NoLogger()
    if args.ignore is None: args.ignore = []

    backend = database.SQLiteDatabase( args.database )
    namelistStore = database.FileDependencies( backend )
    namelistAnalyser = analyser.NamelistDescriptionAnalyser( logger, \
                                                             namelistStore )
    fortranStore = database.FortranDependencies( backend )
    fortranAnalyser = analyser.FortranAnalyser( logger,      \
                                                args.ignore, \
                                                fortranStore )
    if args.source.endswith('.nld'):
        namelistAnalyser.analyse( args.source )
    else:
        fortranAnalyser.analyse( args.source )