#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''
Takes a list of namelists and generates source for a namelist loader.
'''

from __future__ import print_function;

import argparse
import os.path

from configurator import __version__
import configurator.configurationloader as loader
import utilities.logging as logging

if __name__ == '__main__':
    parser = argparse.ArgumentParser( add_help=False, \
                                      description=__doc__ )
    parser.add_argument( '-help', '-h', '--help', action='help', \
                         help='Show this help message and exit' )
    parser.add_argument( '-version', action='version', \
                         version='%(prog)s {}'.format( __version__ ) )
    parser.add_argument( '-verbose', action='store_true', \
                         help='Provide a running commentry' )
    parser.add_argument( 'outputFilename', metavar='output-filename', \
                         help='Source file to produce' )
    parser.add_argument( 'namelistNames', metavar='namelist', \
                         nargs='*', \
                         help='Namelists to load.' )
    args = parser.parse_args()

    if args.verbose:
        logger = logging.PrintLogger( sys.stdout )
    else:
        logger = logging.NoLogger()

    generator = loader.ConfigurationLoader()
    for name in args.namelistNames:
        generator.addNamelist( name )

    with open( args.outputFilename, 'w' ) as moduleFile:
        generator.writeModule( moduleFile )
