#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''
Reads in a namelist description file, produces a Fortran namelist module and
updates the configuration module. Files will be created in the current
directory unless commanded otherwise.
'''

from __future__ import print_function;

import argparse
import os.path

from configurator import __version__
import configurator.namelistdescription as namelist
import utilities.logging as logging

if __name__ == '__main__':
    parser = argparse.ArgumentParser( add_help=False, \
                                      description=__doc__ )
    parser.add_argument( '-help', '-h', '--help', action='help', \
                         help='Show this help message and exit' )
    parser.add_argument( '-version', action='version', \
                         version='%(prog)s {}'.format( __version__ ) )
    parser.add_argument( '-verbose', action='store_true', \
                         help='Provide a running commentry' )
    parser.add_argument( '-directory', metavar='path', default='.', \
                         help='Generated source files are put here.' )
    parser.add_argument( 'descriptionFiles', metavar='description-file', \
                         nargs='*', \
                         help='Dependency details are put here' )
    args = parser.parse_args()

    if args.verbose:
        logger = logging.PrintLogger( sys.stdout )
    else:
        logger = logging.NoLogger()

    descriptionList = []
    parser = namelist.NamelistDescriptionParser()
    for descriptionFilename in args.descriptionFiles:
        with open(descriptionFilename, 'r') as descriptionFile:
            descriptionList.extend( parser.parseFile( descriptionFile ) )

    for description in descriptionList:
        moduleFilename = os.path.join( args.directory, \
                                       description.getModuleName() + '.f90' )
        with open( moduleFilename, 'w' ) as moduleFile:
            description.writeModule( moduleFile )
