##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################

.PHONY: test
test:
	python2.7 -m unittest discover -s dependencyanalysis/tests \
	                               -s configurator/tests \
	                               -p '*test.py'
