class function_space_collection_mod::function_space_collection_type {
  -fs_list: linked_list_type

  <<create>>+function_space_collection_constructor() : function_space_collection_type
  <<destroy>>+function_space_collection_destructor()

  +clear()
  +get_fs( <<in>>mesh_id: integer, <<in>>element_order: integer, <<in>>dynamo_fs: integer) : function_space_type
  +get_fs_collection_size() : integer
}

function_space_collection_mod::function_space_collection_type o-> "*" function_space_mod::function_space_type
