class quadrature_3d_xyz_mod::quadrature_3d_xyz_type {
  -nqp_is_equal: logical
  -nqp_x: integer
  -nqp_y: integer
  -nqp_z: integer
  -nqp_xyz: integer
  -wqp_xyz: real[] <<allocatable>>
  -xqp_xyz: real[::] <<allocatable>>

  +<<create>>init_quadrature_uniform( <<in>>nqp: integer, <<in>>rule: quadrature_rul ) : quadrature_3d_xyz_type
  +<<create>>init_quadrature_variable( <<in>>nqp_x: integer, <<in>>nqp_y: integer, nqp_z: integer<<in>>, <<in>>rule: quadrature_rule ) : quadrature_3d_xyz_type
  +<<destroy>>quadrature_destructor()

  +get_proxy() : quadrature_3d_xyz_proxy_type
}

class quadrature_3d_xyz_mod::quadrature_3d_xyz_proxy_type {
  +nqp_x: integer <<pointer>>
  +nqp_y: integer <<pointer>>
  +nqp_z: integer <<pointer>>
  +nqp_xyz: integer <<pointer>>
  +wqp_xyz: real[] <<pointer>>
  +xqp_xyz: real[::] <<pointer>>
}

quadrature_abstract_mod::quadrature_abstract_type <|-- quadrature_3d_xyz_mod::quadrature_3d_xyz_type
quadrature_3d_xyz_mod::quadrature_3d_xyz_proxy_type -> quadrature_3d_xyz_mod::quadrature_3d_xyz_type
