class quadrature_mod::quadrature_type {
  -nqp_h: integer
  -nqp_v: integer
  -wqp: real[] ><<allocatable>>
  -wqp_h: real[] <<allocatable>>
  -xqp: real[] <<allocatable>>
  -xqp_h: real[] <<allocatable>>

  <<create>>+init_qudarature( <<in>>npoints: integer, <<in>>rule: integer ) : quadrature_type
  <<destroy>>+quadrature_destructor()

  +get_nqp_h() : integer
  +get_nqp_v() : integer
  +get_wqp_h() : real[] <<pointer>>
  +get_wqp_v() : real[] <<pointer>>
  +get_xqp_h() : real[::] <<pointer>>
  +get_xqp_v() : real[] <<pointer>>
  +integrate( f: real[::] ) : real
  +quadrature_rule( <<inout>>quadrature_rule_strategy: quadrature_rule )
  +test_integrate()
}